### ISSUE TITLE
Add function to print a board

### ISSUE THREAD

**Issue by skiadas** [skiadas/haskellMinesweeper#10]
- It should have type `Board -> IO ()`
- You can use the function from #9 . Should do this only after that issue.
- The board should also have a *boundary*. You can build it by using `+-|` or using the box-drawing Unicode symbols: https://en.wikipedia.org/wiki/Box_Drawing_(Unicode_block)   you may need some helper methods for that, for example.
    - A method to build a "horizontal wall" like `+---------+` based on a length and symbol choices. Type `(Char, Char, Char) -> Int -> String`
    - A method to prepend and append a character like `|` to a given string. Type `Char -> String -> String`
- You won't really be able to test the `IO ()` part, so make sure to write tests for your individual helper functions, and to keep the `IO ()` part as clean as possible.

**Comment by btg99** [comment]
Closed by 3d2ff13
