### ISSUE TITLE
Make stringAct safe

### ISSUE THREAD

**Issue by btg99** [skiadas/haskellMinesweeper#18]
use maybe

**Comment by DSkirvinC** [comment]
Changed the type of stringAct from String -> Act to String -> Maybe Act along with relevant changes in the body of said function. stringAct _ now returns Nothing. Added a case expression to makeAction to account for the change in stringAct. These changes pass all new tests. One potential issue is that while it will re-execute makeAction if you provide an invalid input, it does not inform you of this and instead just prompts for new inputs like you never even gave any in the first place.

**Comment by DSkirvinC** [comment]
Check eb47530833bc108d5528ba9be778702b688ed8ee for commit.
