### ISSUE TITLE
show for Board

### ISSUE THREAD

**Issue by btg99** [skiadas/haskellMinesweeper#6]
### Implement
- `show` for `Board`.
- `showSymbol`
    - fancier function to make strings, using some nice unicode characters.

show should simply use `deriving`
Mine = 💣?
Flag = 🚩?

**Comment by skiadas** [comment]
@btg99 I also created a number of other issues related to this one, take a look around. May break this up to those parts instead, and different people can work on different parts.

**Comment by btg99** [comment]
Closed in favor of #8 #9 and #10
