### ISSUE TITLE
Add function to turn cell to character

### ISSUE THREAD

**Issue by skiadas** [skiadas/haskellMinesweeper#7]
- It should have type `Cell -> Char`
- Possible behavior: if state is revealed, then base it on ground values, otherwise base it on state
- Search for unicode Bomb character
- Search for unicode Flag character

**Comment by DSkirvinC** [comment]
* Created a function which converts Cells to Chars titled _**cellToChar**_.
* Managed to find Unicode for a Bomb character, though not sure if it displays properly.
* Managed to find Unicode for a Red Flag character, though also unsure it displays properly.
* Also assigned a question mark to the Questioned status of a Cell, Definitively works.
* Tests are written for and work for the Function titled _**cellToChar**_.
